### ISSUE TITLE
Use user's actual name instead of username for "name" substitution

### ISSUE THREAD

**Issue by ASankaran** [HackIllinois/api-mail#1]
- [ ] Get the user's first name from the user service and use it as the substitution for the "name" key

This will require the user service to add a first name field and the auth service to populate that field with data from the oauth provider.

**Comment by PradyumnaShome** [comment]
Shouldn't it be trivial to query the first and last names once authenticated via OAuth?
I suspect this adding this might end up causing side effects in everything that uses the `UserInfo` struct.

**Comment by ASankaran** [comment]
Retrieving the information is simple, it just requires small patches to multiple services.

See HackIllinois/api-auth#19, HackIllinois/api-user#8, HackIllinois/api-registration#12.

Auth -> User -> Registration / Mailing is the order the patches should be created in.
