### ISSUE TITLE
Add management of mailing lists

### ISSUE THREAD

**Issue by ASankaran** [HackIllinois/api-mail#5]
- [ ] Add support for mailing lists
- [ ] Add endpoint to send templated email to mailing list

Our mailing provider, Sparkpost, does have support for mailing lists. However the api to add and remove users from the list requires us to re-upload the entire list of recipients every time. So I believe the best way for us to manage mailing lists is to locally store a mapping of `list_id => userids[]`. Then when sending to a list we generate substitutions and initiate a Sparkpost transmission.

**Comment by ASankaran** [comment]
We use sparkpost, which does have support for mailing lists that we can hook into.

**Comment by PradyumnaShome** [comment]
- Are you referring to this? https://developers.sparkpost.com/api/recipient-lists

**Comment by ASankaran** [comment]
Yes
